name: Daily Market Close Recap

on:
  schedule:
    # Runs 10 minutes after market close (4:10 PM ET)
    # EDT (March-October): 4:10 PM EDT = 20:10 UTC
    - cron: '10 20 * 3-10 1-5'
    
    # EST (November-February): 4:10 PM EST = 21:10 UTC
    - cron: '10 21 * 11-12,1-2 1-5'
  
  workflow_dispatch:

jobs:
  daily-recap:
    name: Generate Daily Market Recap
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Detect Timezone
        id: timezone
        run: |
          echo "📊 Daily Market Close Recap"
          echo "=========================="
          
          CURRENT_MONTH=$(date -u +%m)
          CURRENT_DAY=$(date -u +%d)
          
          if [ $CURRENT_MONTH -ge 3 ] && [ $CURRENT_MONTH -le 10 ]; then
            if [ $CURRENT_MONTH -eq 3 ] && [ $CURRENT_DAY -lt 8 ]; then
              TZ_NAME="EST"
            elif [ $CURRENT_MONTH -eq 11 ] && [ $CURRENT_DAY -ge 8 ]; then
              TZ_NAME="EST"
            else
              TZ_NAME="EDT"
            fi
          else
            TZ_NAME="EST"
          fi
          
          echo "timezone=$TZ_NAME" >> $GITHUB_OUTPUT
          echo "Timezone: $TZ_NAME"
          echo "UTC: $(date -u '+%Y-%m-%d %H:%M:%S')"
          echo "Eastern: $(TZ='America/New_York' date '+%Y-%m-%d %H:%M:%S %Z')"
          echo "France: $(TZ='Europe/Paris' date '+%Y-%m-%d %H:%M:%S %Z')"
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy requests aiohttp lxml tzdata
      
      - name: Run Daily Recap
        env:
          DISCORD_WEBHOOK_DAILY_RECAP: ${{ secrets.DISCORD_WEBHOOK_DAILY_RECAP }}
          LANGUAGE: ${{ vars.LANGUAGE || 'EN' }}
          DETECTED_TIMEZONE: ${{ steps.timezone.outputs.timezone }}
        run: |
          echo "=========================================="
          echo "S&P 500 Daily Market Close Recap"
          echo "=========================================="
          echo "Timezone: $DETECTED_TIMEZONE"
          echo "Generating comprehensive daily analysis..."
          echo ""
          python sp500_daily_recap.py
          echo ""
          echo "✓ Daily recap completed"
          echo "=========================================="
      
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: daily-recap-logs-${{ github.run_number }}
          path: |
            *.log
            **/*.log
          retention-days: 7
          if-no-files-found: warn
