name: Midnight Market Alert

on:
  schedule:
    # Runs at midnight ET (4:00 UTC during EDT)
    # Tuesday-Saturday (for Monday-Friday predictions)
    - cron: '0 4 * * 2-6'
  
  workflow_dispatch:

jobs:
  midnight-alert:
    name: Send Midnight Market Predictions
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy requests aiohttp lxml
      
      - name: Run Midnight Alert
        env:
          DISCORD_WEBHOOK_MIDNIGHT: ${{ secrets.DISCORD_WEBHOOK_MIDNIGHT }}
          LANGUAGE: ${{ vars.LANGUAGE_BIG_MOVERS || 'EN' }}
        run: |
          echo "🌙 Midnight Market Alert System"
          echo "Analyzing patterns for tomorrow..."
          python sp500_midnight_alert.py
