name: Weekly Market Summary

on:
  schedule:
    # Runs every Saturday at 10:00 AM ET
    # EDT (March-October): 10:00 AM EDT = 14:00 UTC
    - cron: '0 14 * 3-10 6'
    
    # EST (November-February): 10:00 AM EST = 15:00 UTC
    - cron: '0 15 * 11-12,1-2 6'
  
  workflow_dispatch:

jobs:
  weekly-summary:
    name: Generate Weekly Market Summary
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Detect Timezone
        id: timezone
        run: |
          echo "📊 Weekly Market Summary"
          echo "======================="
          
          CURRENT_MONTH=$(date -u +%m)
          CURRENT_DAY=$(date -u +%d)
          
          if [ $CURRENT_MONTH -ge 3 ] && [ $CURRENT_MONTH -le 10 ]; then
            if [ $CURRENT_MONTH -eq 3 ] && [ $CURRENT_DAY -lt 8 ]; then
              TZ_NAME="EST"
            elif [ $CURRENT_MONTH -eq 11 ] && [ $CURRENT_DAY -ge 8 ]; then
              TZ_NAME="EST"
            else
              TZ_NAME="EDT"
            fi
          else
            TZ_NAME="EST"
          fi
          
          echo "timezone=$TZ_NAME" >> $GITHUB_OUTPUT
          echo "Timezone: $TZ_NAME"
          echo "UTC: $(date -u '+%Y-%m-%d %H:%M:%S')"
          echo "Eastern: $(TZ='America/New_York' date '+%Y-%m-%d %H:%M:%S %Z')"
          echo "France: $(TZ='Europe/Paris' date '+%Y-%m-%d %H:%M:%S %Z')"
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy requests aiohttp lxml tzdata
      
      - name: Run Weekly Summary
        env:
          DISCORD_WEBHOOK_WEEKLY: ${{ secrets.DISCORD_WEBHOOK_WEEKLY }}
          LANGUAGE: ${{ vars.LANGUAGE || 'EN' }}
          DETECTED_TIMEZONE: ${{ steps.timezone.outputs.timezone }}
        run: |
          echo "=========================================="
          echo "S&P 500 Weekly Market Summary"
          echo "=========================================="
          echo "Timezone: $DETECTED_TIMEZONE"
          echo "Analyzing past week's market evolution..."
          echo ""
          python sp500_weekly_summary.py
          echo ""
          echo "✓ Weekly summary completed"
          echo "=========================================="
      
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: weekly-summary-logs-${{ github.run_number }}
          path: |
            *.log
            **/*.log
          retention-days: 7
          if-no-files-found: warn
