name: S&P 500 All Variations Monitor

on:
  schedule:
    # Run every 30 minutes during market hours (9:30 AM - 4:00 PM ET)
    # Market hours in UTC: 14:30 - 21:00 (EST) or 13:30 - 20:00 (EDT)
    # This schedule uses EST timezone (Nov-Mar): 14:30 - 21:00 UTC
      - cron: '30 13 * * 1-5'        # 9:30 AM EDT - Market Open
      - cron: '0,30 14-19 * * 1-5'   # Every 30 min
      - cron: '0 20 * * 1-5'         # 4:00 PM EDT - Market Close
    
    # For EDT (Daylight Saving Time, Mar-Nov), uncomment this instead:
    # - cron: '30,0 13-19 * * 1-5'
    # - cron: '0 20 * * 1-5'
  
  # Allow manual trigger from Actions tab
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  monitor-all-variations:
    name: Monitor All Market Variations
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-all-variations-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-all-variations-
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy requests aiohttp lxml
      
      - name: Run All Variations Monitor
        env:
          DISCORD_WEBHOOK_ALL_VARIATIONS: ${{ secrets.DISCORD_WEBHOOK_ALL_VARIATIONS }}
          BATCH_SIZE: ${{ vars.BATCH_SIZE || '50' }}
        run: |
          echo "=========================================="
          echo "S&P 500 All Variations Monitor"
          echo "=========================================="
          echo "Start Time: $(date)"
          echo "Analyzing all 500+ stocks..."
          echo ""
          python sp500_all_variations.py
          echo ""
          echo "Completed: $(date)"
          echo "=========================================="
      
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: all-variations-logs-${{ github.run_number }}
          path: |
            *.log
            **/*.log
          retention-days: 7
          if-no-files-found: warn
